spring.application.name=student-jdbc-app

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Ensure schema.sql runs on startup
spring.sql.init.mode=always

# Useful during development
spring.jpa.show-sql=false
server.port=8080
